version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_tests_challenge
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: fin_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
